public class DnaFind {
    public static int find(String look, char c){
        int val=0;
        for(int i=0;i<look.length() ;i++){
            if(look.charAt(i)==c){
                val++;
            }
        }
        return val;
    }
    public static int find2(String look, char c){
        int val = look.length();
        String x= String.valueOf(c);
        String look2 = look.replaceAll(x,"");
        val = val-look2.length();
        return val;
    }

    public static void main(String[] args){
        String text="AGACCCGCACAGCTGTAAGGGTTCATCTCGTTCATACCATTTGGTGGCGCGATGTTTCACCCGTACTTTTGAGGACTTTACAGGTGATCCGATGGCGTCAGCTGAAATAGTACGCCCGATTTTTGAGGCTCCTCTACTGTCGATAGTAGTGGACCATAGTAGTAACCTGCGATTAACTTCGTGGCTTTAAACGCGGATTGGCCACAACGTCGGTCATTCTAGTCGCACGAAAGTTCGTCTCGTATCTTGTCTTGCTTTTTCGGCGTGCCTGACTGTTGCCTATCTGTTAATCGGATCCCCCTGCACACTACTCTTGTCCGCGGTGGGCCACGTATAGTTGCGGTAATCGTGGACAACTGAAATCAGGAGCCTAGTACAATAGCTTGGTGAGTCTGGTTTACTAGCACAACGTGTTCTGTGAATATGCTGAAGTGTCTATGCCTTAGTCGAAATAAGATAGTGCTTCCAGTCTACCCTCTGCCACGCACACCTTTTGTGCATCTTCGTGGTTCGGGTCGGCGAGACATATAGTCTTCTGATCGGCCTGTCAAGTGTTACGATCGCGCCCCACTGATATTTATGCCTCTCCTCCGGCTCGCATCCCTGAATACCAACGAATGGTCGTCTGAGACTGTCCATTTGTCACTAGCGCTCTGATAGGGCAGTTCGGACCAGCTAGAGTCTAACTGGACAGATTCCCGAGCTCTTAAACGTACCCACGGAGGGGGAGGATAGAAAGCGATCGATTACCCCTCGTGGTAGAAATGAATAAGACGTCCTATATTGTCTTACCCTAGTCCAGCGGCTTCGTATAACCTCCCGATTCATCAAGTGAGCCCTACGGCAAGTTAGCACCATAGGAATTGGTTACCCATCCGAGAAGCGAAGGCGCACTTACAAAGGCATCTGCCTAGCGACGCAGAGCCAACCGTTAAGGAATGCCCT";
        int a,c,g,t;
        a= find2(text,'A');
        c= find2(text,'C');
        g= find2(text,'G');
        t= find2(text,'T');
        System.out.println("a has "+a+"c has "+c+"g has "+g+"t has "+t );
    }
}
